### ISSUE TITLE
replica

### ISSUE THREAD

**Issue by kapmen** [jcreinhold/synthit#2]
I saw your open source code of REPLICA based on MATLAB.
Is this Synthit different from REPLICA?
If they are same, is there a performance difference between MATLAB based program and this Synthit?

Please answer me.

**Comment by jcreinhold** [comment]
This is not exactly the same as REPLICA. The MATLAB version more closely follows the corresponding paper; however, the random forest implementation of synthesis in this package, along with the proper options, is _very_ close to REPLICA and I've had better performance using this formulation.
